### ISSUE TITLE
SSO & AU Http StatusCode Handling

### ISSUE THREAD

**Issue by digulla** [zkoss/zk#583]
This is related to http://forum.zkoss.org/question/13182/authentication-au-http-statuscode-handling/ which contains a patch.

In a nutshell: I'm using Fediz as an Single-Sign-On (SSO) service. When the SSO token times out, I see this in the log file:

    [timestamp] "POST /webapp/zkau HTTP/1.1" 302

The code in au.js doesn't handle this case. Instead of redirecting the to start or timeout page, it tries again.

Instead, the code should either follow the redirection or it should be possible to define a timeout/logout URL in `zk.xml`.

**Comment by cor3000** [comment]
Hi,
thanks for the input, I had the same idea before. The problem is a 302 cannot be handled when using Ajax. the browser will handle the 302 transparently for you (unless you perform some OS/browser specific configuration) and the response will likely be an HTML document (sso login page, code 200), that doesn't make sense to the ZK client engine, so it retries.
Another issue is that most SSO filter reject the request even before they reach the ZK servlet, leaving no chance to react on the server side as well.

http://stackoverflow.com/a/15996968/4740707
It is recommended to respond with a 401 instead (that way the error can be handled on the client side).
Errors can be handled overriding the ajaxErrorHandler 
https://www.zkoss.org/javadoc/8.0.0/jsdoc/_global_/zAu.html#ajaxErrorHandler(java.lang.Object,%20int,%20_global_.String,%20int)

also see: https://github.com/zkoss/zk/blob/199b4a5434391ba3040767594f0afcab3bcf0802/zk/src/archive/web/js/zk/au.js#L193

**Comment by digulla** [comment]
I created a gist with the necessary code: https://gist.github.com/digulla/5c0d80bccde266f7fe84c0529379044d
