### ISSUE TITLE
Allow to call JavaScript function in error-reload

### ISSUE THREAD

**Issue by digulla** [zkoss/zk#602]
This is related to #583 SSO & AU Http StatusCode Handling

Currently, I can only redirect to an URI. This causes a problem in my case:
1. Session times out
2. Server sends 401 to client
3. ZK error handling code tries to load /timeout.zul
4. Server redirects request for /timeout.zul to SSO server since you don't have a valid login, yet.

This means I can't display a nice message to the user when a SSO timeout happens because I can't load any pages.

I would like to be able to call JavaScript when an error happens. That would allow me to display a message when a timeout happens.

Workaround: If you can split the application URLs into public and secure ones, then you could put the timeout URL into the public area.

Unfortunately, in my case, the root URL has to be secure, and I couldn't figure out how to say "/timeout.zul is public" when "/" is secure.

**Comment by cor3000** [comment]
Hi Aaron, 
first off: for questions and discussions we have our [forum](http://forum.zkoss.org/questions/), which we follow actively (or ou premium [support ](https://www.zkoss.org/support/)).

Nevertheless here how to customize ZK's [timeout handling](https://www.zkoss.org/wiki/ZK_Developer's_Reference/UI_Patterns/Session_Timeout_Management#Total_Control_in_JavaScript) and use any arbitrary JS instead of redirecting. Maybe that's the missing piece.

About your workaround: the possibility of this approach depends mainly on where your SSO handling occurs. 

If outside the application container (e.g. in apache httpd, or nginx) then there's no chance within the webapp.

If inside a filter in the same webapp then very often those SSO filters have an exclude option ([one reply here shows how to do it in e.g. apache shiro](http://stackoverflow.com/questions/15024235/how-to-exclude-one-url-from-authorization)).
If not it's possible to subclass the SSO filter and [omit the authentication checks for certain URLs](http://stackoverflow.com/questions/3125296/can-i-exclude-some-concrete-urls-from-url-pattern-inside-filter-mapping).

**Comment by cor3000** [comment]
SSO handling improved by related issues:
https://tracker.zkoss.org/browse/ZK-4199 (8.6.2)
https://tracker.zkoss.org/browse/ZK-4175 (9.5.0)
